# Changes here will be overwritten by Copier
_commit: v0.10.7
_src_path: https://github.com/fohte/generic-boilerplate
auto_merge_release_pr: false
description: '@fohte''s personal GitHub Actions workflows for Storybook visual regression
    testing'
is_public: true
project_name: storybook-vrt-workflows
release_type: simple
repo_id: '1339719353'
repo_language: en
subpackages: []
type: base
use_release_please: true
