issuer: https://token.actions.githubusercontent.com
subject_pattern: ^repo:fohte@11088009/storybook-vrt-workflows@1339719353:ref:refs/heads/.+$
claim_pattern:
  job_workflow_ref: ^fohte/storybook-vrt-workflows/\.github/workflows/test\.yml@[^@]+$
permissions:
  contents: write
